CREATE TABLE IF NOT EXISTS `TSD` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Asset` VARCHAR(64),
    `Symbol` VARCHAR(16),
    `Date` DATE NOT NULL,
    `Open` DECIMAL(16, 6),
    `High` DECIMAL(16, 6),
    `Low` DECIMAL(16, 6),
    `Close` DECIMAL(16, 6),
    `Volume` BIGINT,
    `SMA7` DECIMAL(16, 6),
    `SMA20` DECIMAL(16, 6),
    `SMA50` DECIMAL(16, 6),
    `SMA100` DECIMAL(16, 6),
    `SMA200` DECIMAL(16, 6),
    `RSI` DECIMAL(16, 6),
    `MACD` DECIMAL(16, 6),
    `MACD_Histogram` DECIMAL(16, 6),
    `MACD_Signal` DECIMAL(16, 6),
    `BollingerBands_Center` DECIMAL(16, 6),
    `BollingerBands_Upper` DECIMAL(16, 6),
    `BollingerBands_Lower` DECIMAL(16, 6),
    `BollingerBands_Percent` DECIMAL(16, 6),
    `BollingerBands_ZScore` DECIMAL(16, 6),
    `BollingerBands_Width` DECIMAL(16, 6),
    INDEX(`Asset`));